version: "3"
services:
  haproxy:
    build:
      context: ./haproxy
    volumes:
      - "./haproxy:/usr/local/etc/haproxy:ro"
    ports:
      - "5000:5000"

  app1:
    build:
      context: ./app
    volumes:
      - "./app:/app:ro"
    working_dir: /app
    command: ["server.py"]
    environment:
      SERVER_ID: SERVER_1

  app2:
    build:
      context: ./app
    volumes:
      - "./app:/app:ro"
    working_dir: /app
    command: ["server.py"]
    environment:
      SERVER_ID: SERVER_2
